CREATE TABLE IF NOT EXISTS endpoint_hits (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app VARCHAR(125) NOT NULL,
    uri VARCHAR(125) NOT NULL,
    ip VARCHAR(125) NOT NULL,
    timestamp TIMESTAMP NOT NULL
);